name: Sync to Hugging Face hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: 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
        run: git push --force https://huggingface.co/spaces/BhagwatK/Text_to_Image_Generator main

